# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  schema_search_path: public
  postgis_extension: postgis

development:
  <<: *default
  database: commet_development
  username: postgres
  password: postgres
  host: localhost
 
test:
  adapter: postgresql
  encoding: unicode
  database: commet_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: commet_production
  pool: 5
  username: postgres
  password: postgres




